TARGETS= simplest.$(PDSUFFIX) \
		 simplest_01.$(PDSUFFIX) \
		 mem_0.$(PDSUFFIX) \
		 mem_1.$(PDSUFFIX) \
		 fifo_0.$(PDSUFFIX) \
		 nop_tilde_0.$(PDSUFFIX)
		 
OBJECTS= $(TARGETS:$(PDSUFFIX)=o)

DARWINARCH= -fPIC -arch i386 -arch x86_64
PDSUFFIX=pd_darwin
CFLAGS=$(DARWINARCH) -c -g
LDFLAGS=$(DARWINARCH) -bundle -undefined suppress -flat_namespace
LD=$(CC)

all: $(TARGETS)

clean:
	$(RM) $(OBJECTS) $(TARGETS)
	
.SUFFIXES: .$(PDSUFFIX) .o
	
%.$(PDSUFFIX): %.o
	$(LD) $(LDFLAGS) -o $@ $< -lm